<?php

/**
 * @file
 * hc_standard_homepage module file.
 */

 use Drupal\Core\Routing\RouteMatchInterface;


 /**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hc_standard_homepage_embed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hc_standard_homepage':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
* Implements hook_preprocess_node().
* @param $variables
*/
function hc_standard_homepage_preprocess_node(&$variables) {

  $node = $variables['elements']['#node'];

  $variables['show_intro_section'] = true;
  if ($node->hasField('field_hc_hide_intro_section')) {
    $value = $node->get('field_hc_hide_intro_section')->getValue();
    if($value[0]['value'] == '1') {
      $variables['show_intro_section'] = false;
    }
  }

  $variables['show_intro_sidebar'] = true;
  if ($node->hasField('field_hc_hide_intro_sidebar')) {
    $value = $node->get('field_hc_hide_intro_sidebar')->getValue();
    if($value[0]['value'] == '1') {
      $variables['show_intro_sidebar'] = false;
    }
  }

}


// UPDATES
//////////////////////////////////////////////////////


/**
 * Updates to allow hiding sections. Update 8001 contained errors, so jumping a level here.
 */
function hc_standard_homepage_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'hc_standard_homepage');
}