<?php

/**
 * @file
 * Hc_standard_homepage module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\media\Entity\Media;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hc_standard_homepage_embed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hc_standard_homepage':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_node().
 */
function hc_standard_homepage_preprocess_node(&$variables) {

  $node = $variables['elements']['#node'];
  $bundle = $node->bundle();
  if ($bundle == 'hc_standard_homepage') {
    // Sets type, intro or video/image.
    $variables['hero_display_type'] = 'standard_intro';
    if ($node->hasField('field_hc_hero_display_options')) {
      $value = $node->get('field_hc_hero_display_options')->getValue();
      $value = $value[0]['value'];
      $variables['hero_display_type'] = $value;
    }

    // Sets type, image or video.
    $variables['hero_media_display_type'] = 'image';
    if ($node->hasField('field_hc_media_display_options')) {
      $value = $node->get('field_hc_media_display_options')->getValue();
      $value = $value[0]['value'];
      $variables['hero_media_display_type'] = $value;
    }

    // Adds ability to hide intro sidebar.
    $variables['show_intro_sidebar'] = TRUE;
    if ($node->hasField('field_hc_hide_intro_sidebar')) {
      $value = $node->get('field_hc_hide_intro_sidebar')->getValue();
      if ($value[0]['value'] == '1') {
        $variables['show_intro_sidebar'] = FALSE;
      }
    }

    // Hide overlay on full width image/video.
    $variables['hide_overlay'] = FALSE;
    if ($node->hasField('field_hc_hide_overlay')) {
      $value = $node->get('field_hc_hide_overlay')->getValue();
      if ($value[0]['value'] == '1') {
        $variables['hide_overlay'] = TRUE;
      }
    }

    // Homepage background video.
    $variables['hero_media_video'] = _hc_standard_homepage_load_vimeo_video_background($node, 'field_hc_header_video');

    // Homepage Intro Background Image.
    $variables['home_intro_image'] = '/themes/contrib/hu_general/idfive-component-library/build/img/graduates_talking.jpg';
    if ($node->hasField('field_hc_intro_background_image')) {
      $bckrd_image = $node->get('field_hc_intro_background_image')->getValue();
      if ($bckrd_image && !empty($bckrd_image)) {
        $entity = Media::load($bckrd_image[0]['target_id']);
        if (isset($entity->field_media_image->entity)) {
          $variables['home_intro_image'] = ImageStyle::load('hc_hero_image')->buildUrl($entity->field_media_image->entity->getFileUri());
        }
      }
    }

    // Homepage Full width Background Image.
    if ($node->hasField('field_hc_header_image')) {
      $home_hero_image = $node->get('field_hc_header_image')->getValue();
      if ($home_hero_image && !empty($home_hero_image)) {
        $entity = Media::load($home_hero_image[0]['target_id']);
        if (isset($entity) && $entity->field_media_image->entity !== NULL && $entity->field_media_image->entity->getFileUri() !== NULL) {
          $variables['home_hero_image'] = file_create_url($entity->field_media_image->entity->getFileUri());
        }
      }
    }

    // Homepage school wide announcements.
    $variables['announcements'] = \Drupal::service('howard.news')->getAnnouncements();

  }
}

/**
 * Gets vimeo video and modifies for background use.
 */
function _hc_standard_homepage_load_vimeo_video_background($node, $field) {
  if ($node->hasField($field)) {
    $video = $node->get($field)->getValue();
    if ($video && !empty($video)) {
      $entity = Media::load($video[0]['target_id']);
      if ($entity->hasField('field_media_oembed_video')) {
        // If remote video.
        $video_url = $entity->field_media_oembed_video->value;
        // If vimeo.
        if (strpos($video_url, 'vimeo') !== FALSE) {
          $video_url = preg_replace('/[^0-9]/', '', $video_url);
          return $video_url;
        }
      }
    }
  }
}
