<?php

/**
 * @file
 * Hc_resources install file.
 */

use Drupal\taxonomy\Entity\Term;
use Drupal\taxonomy\Entity\Vocabulary;


/**
 * Implements hook_install().
 *
 * Creates default terms.
 */
function hc_resources_install() {
  _hc_resources_create_resource_terms();
}

/**
 * Implements hook_uninstall().
 *
 * Removes content type.
 */
function hc_resources_uninstall() {
  _hc_resources_remove_entity_and_content();
}

/**
 * Updates to media browser, taxonomies, etc.
 */
function _hc_resources_create_resource_terms() {
  $categories = [
    'Student Resources',
    'Alumni Resources',
    'Faculty & Staff Resources',
  ];
  foreach ($categories as $category) {
    $term = Term::create([
      'parent' => [],
      'name' => $category,
      'vid' => 'hc_resource_category',
    ])->save();
  }
}

/**
 * Remove all resource nodes, remove content type, remove vocabulary.
 */
function _hc_resources_remove_entity_and_content() {
  // Delete hc_resource nodes.
  $storage_handler = \Drupal::entityTypeManager()
    ->getStorage('node');
  $nodes = $storage_handler->loadByProperties(['type' => 'hc_resource']);
  $storage_handler->delete($nodes);
  // Delete hc_resource content type.
  $content_type = \Drupal::entityTypeManager()
    ->getStorage('node_type')
    ->load('hc_resource');
  $content_type->delete();
  // Delete hc_resource_category vocabulary.
  $vocab = Vocabulary::load('hc_resource_category');
  if ($vocab) {
    $vocab->delete();
  }
}

/**
 * Change display form to close ks widgets
 */
function hc_resources_update_8007()
{
  \Drupal::service('config.installer')->installDefaultConfig('module', 'hc_resources');
}

/**
 * Enable paragraph types by default and improve form, view
 */
function hc_resources_update_8008()
{
  \Drupal::service('config.installer')->installDefaultConfig('module', 'hc_resources');
}

/**
 * Updates to add moderation sections to all content types.
 */
function hc_resources_update_8009() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'hc_resources');
}

/**
 * Updates to allow resources view to accept multiple values, https://trello.com/c/WTNRqiiA/916-resources-widget-concatenation-of-multiple-resources-when-limited-by-category.
 */
function hc_resources_update_8010() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'hc_resources');
}

/**
 * Updates to allow resources view to accept multiple values, https://trello.com/c/WTNRqiiA/916-resources-widget-concatenation-of-multiple-resources-when-limited-by-category.
 */
function hc_resources_update_8011() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'hc_resources');
}